const ROLES = [
  { name: "admin" },
  { name: "user" },
  { name: "management" },
  { name: "accountant" },
  { name: "sale" },
];

const ROOMTYPES = [
  { type_name: "Single Room", type_code: "TYPE-001" },
  { type_name: "Double Room", type_code: "TYPE-002" },
  { type_name: "Luxary Room", type_code: "TYPE-003" },
  { type_name: "Suite Room", type_code: "TYPE-004" },
];

const STATE = [
  { state_name: "Banteay Meanchey" },
  { state_name: "Battambang" },
  { state_name: "Kampong Cham" },
  { state_name: "Kampong Chhnang" },
  { state_name: "Kampong Speu" },
  { state_name: "Kampong Thom" },
  { state_name: "Kandal" },
  { state_name: "Kampot" },
  { state_name: "Koh Kong" },
  { state_name: "Kratié" },
  { state_name: "Mondulkiri" },
  { state_name: "Phnom Penh" },
  { state_name: "Prey Veng" },
  { state_name: "Preah Vihear" },
  { state_name: "Pursat" },
  { state_name: "Ratanakiri" },
  { state_name: "Siem Reap" },
  { state_name: "Preah Sihanouk" },
  { state_name: "Stung Treng" },
  { state_name: "Svay Rieng" },
  { state_name: "Takéo" },
  { state_name: "Oddar Meanchey" },
  { state_name: "Kep" },
  { state_name: "Pailin" },
  { state_name: "Tboung Khmum" },
];

const CITY = [
  { city_name: "Mongkol Borei", state_id: 1 },
  { city_name: "Phnum Srok", state_id: 1 },
  { city_name: "Ou Chrov", state_id: 1 },
  { city_name: "Serei Saophoan", state_id: 1 },
  { city_name: "Thma Puok", state_id: 1 },
  { city_name: "Svay Chek", state_id: 1 },
  { city_name: "Malai", state_id: 1 },
  { city_name: "Paoy Paet", state_id: 1 },
  { city_name: "Banan", state_id: 2 },
  { city_name: "Thma Koul", state_id: 2 },
  { city_name: "Battambang", state_id: 2 },
  { city_name: "Bavel", state_id: 2 },
  { city_name: "Aek Phnum", state_id: 2 },
  { city_name: "Moung Ruessei", state_id: 2 },
  { city_name: "Rotonak Mondol", state_id: 2 },
  { city_name: "Sangkae", state_id: 2 },
  { city_name: "Samlout", state_id: 2 },
  { city_name: "Sampov Lun", state_id: 2 },
  { city_name: "Phnum Proek", state_id: 2 },
  { city_name: "Kamrieng", state_id: 2 },
  { city_name: "Koas Krala", state_id: 2 },
  { city_name: "Rukh Kiri", state_id: 2 },
  { city_name: "Batheay", state_id: 3 },
  { city_name: "Chamkar Leu", state_id: 3 },
  { city_name: "Cheung Prey", state_id: 3 },
  { city_name: "Kampong Cham", state_id: 3 },
  { city_name: "Kampong Siem", state_id: 3 },
  { city_name: "Kang Meas", state_id: 3 },
  { city_name: "Kaoh Soutin", state_id: 3 },
  { city_name: "Prey Chhor", state_id: 3 },
  { city_name: "Srei Santhor", state_id: 3 },
  { city_name: "Stueng Trang", state_id: 3 },
  { city_name: "Baribour", state_id: 4 },
  { city_name: "Chol Kiri", state_id: 4 },
  { city_name: "Kampong Chhnang", state_id: 4 },
  { city_name: "Kampong Leaeng", state_id: 4 },
  { city_name: "Kampong Tralach", state_id: 4 },
  { city_name: "Rolea B'ier", state_id: 4 },
  { city_name: "Sameakki Mean Chey", state_id: 4 },
  { city_name: "Tuek Phos", state_id: 4 },
  { city_name: "Basedth", state_id: 5 },
  { city_name: "Chbar Mon", state_id: 5 },
  { city_name: "Kong Pisei", state_id: 5 },
  { city_name: "Aoral", state_id: 5 },
  { city_name: "Phnum Sruoch", state_id: 5 },
  { city_name: "Samraong Tong", state_id: 5 },
  { city_name: "Thpong", state_id: 5 },
  { city_name: "Odongk Maechay", state_id: 5 },
  { city_name: "Samkkei Munichay", state_id: 5 },
  { city_name: "Baray", state_id: 6 },
  { city_name: "Kampong Svay", state_id: 6 },
  { city_name: "Stueng Saen", state_id: 6 },
  { city_name: "Prasat Ballangk", state_id: 6 },
  { city_name: "Prasat Sambour", state_id: 6 },
  { city_name: "Sandan", state_id: 6 },
  { city_name: "Santuk", state_id: 6 },
  { city_name: "Stoung", state_id: 6 },
  { city_name: "Kandal Stueng", state_id: 7 },
  { city_name: "Kien Svay", state_id: 7 },
  { city_name: "Khsach Kandal", state_id: 7 },
  { city_name: "Kaoh Thum", state_id: 7 },
  { city_name: "Leuk Daek", state_id: 7 },
  { city_name: "Lvea Aem", state_id: 7 },
  { city_name: "Mukh Kampul", state_id: 7 },
  { city_name: "Angk Snuol", state_id: 7 },
  { city_name: "Ponhea Lueu", state_id: 7 },
  { city_name: "S'ang", state_id: 7 },
  { city_name: "Ta Khmau", state_id: 7 },
  { city_name: "Sampeou Poun", state_id: 7 },
  { city_name: "Akreiy Ksatr", state_id: 7 },
  { city_name: "Angkor Chey", state_id: 8 },
  { city_name: "Banteay Meas", state_id: 8 },
  { city_name: "Chhuk", state_id: 8 },
  { city_name: "Chum Kiri", state_id: 8 },
  { city_name: "Dang Tong", state_id: 8 },
  { city_name: "Kampong Trach", state_id: 8 },
  { city_name: "Tuek Chhou", state_id: 8 },
  { city_name: "Kampot", state_id: 8 },
  { city_name: "Bokor", state_id: 8 },
  { city_name: "Botum Sakor", state_id: 9 },
  { city_name: "Kiri Sakor", state_id: 9 },
  { city_name: "Kaoh Kong", state_id: 9 },
  { city_name: "Srae Ambel", state_id: 9 },
  { city_name: "Thma Bang", state_id: 9 },
  { city_name: "Chhloung", state_id: 10 },
  { city_name: "Kracheh", state_id: 10 },
  { city_name: "Prek Prasab", state_id: 10 },
  { city_name: "Sambour", state_id: 10 },
  { city_name: "Snuol", state_id: 10 },
  { city_name: "Chetr Borei", state_id: 10 },
  { city_name: "Ou Krieng Saenchey", state_id: 10 },
  { city_name: "Kaev Seima", state_id: 11 },
  { city_name: "Kaoh Nheaek", state_id: 11 },
  { city_name: "Ou Reang", state_id: 11 },
  { city_name: "Pech Chreada", state_id: 11 },
  { city_name: "Saen Monourom", state_id: 11 },
  { city_name: "Chamkar Mon", state_id: 12 },
  { city_name: "Doun Penh", state_id: 12 },
  { city_name: "Prampir Meakkakra", state_id: 12 },
  { city_name: "Tuol Kouk", state_id: 12 },
  { city_name: "Dangkao", state_id: 12 },
  { city_name: "Mean Chey", state_id: 12 },
  { city_name: "Russey Keo", state_id: 12 },
  { city_name: "Saensokh", state_id: 12 },
  { city_name: "Pur SenChey", state_id: 12 },
  { city_name: "Chrouy Changvar", state_id: 12 },
  { city_name: "Praek Pnov", state_id: 12 },
  { city_name: "Chbar Ampov", state_id: 12 },
  { city_name: "Kamboul", state_id: 12 },
  { city_name: "Ba Phnum", state_id: 13 },
  { city_name: "Kamchay Mear", state_id: 13 },
  { city_name: "Kampong Trabaek", state_id: 13 },
  { city_name: "Kanhchriech", state_id: 13 },
  { city_name: "Me Sang", state_id: 13 },
  { city_name: "Peam Chor", state_id: 13 },
  { city_name: "Peam Ro", state_id: 13 },
  { city_name: "Pea Reang", state_id: 13 },
  { city_name: "Preah Sdach", state_id: 13 },
  { city_name: "Prey Veng", state_id: 13 },
  { city_name: "Pur Rieng", state_id: 13 },
  { city_name: "Sithor Kandal", state_id: 13 },
  { city_name: "Svay Antor", state_id: 13 },
  { city_name: "Chey Saen", state_id: 14 },
  { city_name: "Chhaeb", state_id: 14 },
  { city_name: "Choam Ksant", state_id: 14 },
  { city_name: "Kuleaen", state_id: 14 },
  { city_name: "Rovieng", state_id: 14 },
  { city_name: "Sangkum Thmei", state_id: 14 },
  { city_name: "Tbaeng Mean Chey", state_id: 14 },
  { city_name: "Preah Vihear", state_id: 14 },
  { city_name: "Bakan", state_id: 15 },
  { city_name: "Kandieng", state_id: 15 },
  { city_name: "Krakor", state_id: 15 },
  { city_name: "Phnum Kravanh", state_id: 15 },
  { city_name: "Pursat", state_id: 15 },
  { city_name: "Veal Veaeng", state_id: 15 },
  { city_name: "Ta Lou Senchey", state_id: 15 },
  { city_name: "Andoung Meas", state_id: 16 },
  { city_name: "Ban Lung", state_id: 16 },
  { city_name: "Bar Kaev", state_id: 16 },
  { city_name: "Koun Mom", state_id: 16 },
  { city_name: "Lumphat", state_id: 16 },
  { city_name: "Ou Chum", state_id: 16 },
  { city_name: "Ou Ya Dav", state_id: 16 },
  { city_name: "Ta Veaeng", state_id: 16 },
  { city_name: "Veun Sai", state_id: 16 },
  { city_name: "Angkor Chum", state_id: 17 },
  { city_name: "Angkor Thum", state_id: 17 },
  { city_name: "Banteay Srei", state_id: 17 },
  { city_name: "Chi Kraeng", state_id: 17 },
  { city_name: "Kralanh", state_id: 17 },
  { city_name: "Puok", state_id: 17 },
  { city_name: "Prasat Bakong", state_id: 17 },
  { city_name: "Siem Reap", state_id: 17 },
  { city_name: "Soutr Nikom", state_id: 17 },
  { city_name: "Srei Snam", state_id: 17 },
  { city_name: "Svay Leu", state_id: 17 },
  { city_name: "Varin", state_id: 17 },
  { city_name: "Run Ta Aek Techo Sen", state_id: 17 },
  { city_name: "Preah Sihanouk", state_id: 18 },
  { city_name: "Prey Nob", state_id: 18 },
  { city_name: "Stueng Hav", state_id: 18 },
  { city_name: "Kampong Seila", state_id: 18 },
  { city_name: "Kaoh Rung", state_id: 18 },
  { city_name: "Kampong Soam", state_id: 18 },
  { city_name: "Sesan", state_id: 19 },
  { city_name: "Siem Bouk", state_id: 19 },
  { city_name: "Siem Pang", state_id: 19 },
  { city_name: "Stueng Traeng", state_id: 19 },
  { city_name: "Thala Barivat", state_id: 19 },
  { city_name: "Borei Ou Svay Senchey", state_id: 19 },
  { city_name: "Chantrea", state_id: 20 },
  { city_name: "Kampong Rou", state_id: 20 },
  { city_name: "Rumduol", state_id: 20 },
  { city_name: "Romeas Haek", state_id: 20 },
  { city_name: "Svay Chrum", state_id: 20 },
  { city_name: "Svay Rieng", state_id: 20 },
  { city_name: "Svay Teab", state_id: 20 },
  { city_name: "Bavet", state_id: 20 },
  { city_name: "Angkor Borei", state_id: 21 },
  { city_name: "Bati", state_id: 21 },
  { city_name: "Borei Cholsar", state_id: 21 },
  { city_name: "Kiri Vong", state_id: 21 },
  { city_name: "Kaoh Andaet", state_id: 21 },
  { city_name: "Prey Kabbas", state_id: 21 },
  { city_name: "Samraong", state_id: 21 },
  { city_name: "Doun Kaev", state_id: 21 },
  { city_name: "Tram Kak", state_id: 21 },
  { city_name: "Treang", state_id: 21 },
  { city_name: "Anlong Veaeng", state_id: 22 },
  { city_name: "Banteay Ampil", state_id: 22 },
  { city_name: "Chong Kal", state_id: 22 },
  { city_name: "Samraong", state_id: 22 },
  { city_name: "Trapeang Prasat", state_id: 22 },
  { city_name: "Damnak Chang'aeur", state_id: 23 },
  { city_name: "Kaeb", state_id: 23 },
  { city_name: "Pailin", state_id: 24 },
  { city_name: "Sala Krau", state_id: 24 },
  { city_name: "Dambae", state_id: 25 },
  { city_name: "Krouch Chhmar", state_id: 25 },
  { city_name: "Memot", state_id: 25 },
  { city_name: "Ou Reang Ov", state_id: 25 },
  { city_name: "Ponhea Kraek", state_id: 25 },
  { city_name: "Suong", state_id: 25 },
  { city_name: "Tboung Khmum", state_id: 25 },
];

module.exports = { ROOMTYPES, ROLES, STATE, CITY };
