const modelSchemas = {
  role: {
    roleId: "String",
    name: "String",
  },
  auth: {
    authId: "String",
    email: "String",
    password: "String",
    roleId: "String",
    employeeId: "String",
    customerId: "String",
    status: "String",
  },
  attendace: {
    attendaceId: "String",
    employeeId: "String",
    datetime: "Date",
    note: "String",
  },
  employee: {
    employeeId: "String",
    employeeCode: "String",
    firstName: "String",
    lastName: "String",
    gender: "String",
    dob: "DateTime",
    phone: "String",
    positionId: "String",
    departmentId: "String",
    salary: "Int",
    hiredDate: "DateTime",
    status: "String",
  },
  employeeInfo: {
    infoId: "String",
    employeeId: "String",
    picture: "String",
    region: "String",
    email: "String",
    address: "String",
    cityId: "String",
    stateId: "String",
    country: "String",
    note: "String",
  },
  department: {
    departmentId: "String",
    departmentName: "String",
    departmentCode: "String",
    memo: "String",
    status: "String",
  },
  position: {
    positionId: "String",
    departmentId: "String",
    positionName: "String",
    positionCode: "String",
    memo: "String",
    status: "String",
  },
  customer: {
    customerId: "String",
    firstName: "String",
    lastName: "String",
    picture: "String",
    gender: "String",
    email: "String",
    phone: "String",
    address: "String",
    cityId: "String",
    stateId: "String",
    status: "String",
  },
  reservationDetail: {
    reserveDetailId: "String",
    roomId: "String",
    employeeId: "String",
    customerId: "String",
    reservationId: "String",
    price: "Decimal",
    night: "Int",
    amount: "Decimal",
  },
  reservation: {
    reservationId: "String",
    checkinDate: "Date",
    checkoutDate: "Date",
    isCheckin: "Boolean",
    isCheckout: "Boolean",
    reservationType: "String",
    adults: "Int",
    children: "Int",
    paymentStatus: "String",
    paymentMethod: "String",
    memo: "String",
    status: "String",
  },
  room: {
    roomId: "String",
    roomtypeId: "String",
    roomName: "String",
    price: "Decimal",
    isAc: "Boolean",
    capacity: "Int",
    size: "Int",
    discountRate: "Int",
    isBooked: "Boolean",
    status: "String",
  },
  roomType: {
    roomtypeId: "String",
    typeName: "String",
    typeCode: "String",
  },
  product: {
    productId: "String",
    productName: "String",
    productCode: "String",
    productCategoryId: "String",
    picture: "String",
    price: "Decimal",
    discountRate: "Int",
    status: "String",
  },
  productCategory: {
    productCategoryId: "String",
    picture: "String",
    categoryName: "String",
    categoryCode: "String",
    memo: "String",
    status: "String",
  },
  cart: {
    cartId: "String",
    authId: "String",
    productId: "String",
    quantity: "Int",
  },
  cartNote: {
    noteId: "String",
    cartId: "String",
    note: "String",
  },
  productStock: {
    productStockId: "String",
    productId: "String",
    supplierId: "String",
    invNumber: "String",
    productAdd: "Int",
    add_price: "Decimal",
    addDate: "Date",
    memo: "String",
    status: "String",
  },
  supplier: {
    supplierId: "String",
    supplierName: "String",
    companyName: "String",
    phone: "String",
    email: "String",
    address: "String",
    status: "String",
    createdAt: "Date",
  },
  sale: {
    saleId: "String",
    employeeId: "String",
    roomId: "String",
    customerId: "String",
    saleDate: "Date",
    amount: "Decimal",
    status: "String",
  },
  saleDetail: {
    saleDetailId: "String",
    saleId: "String",
    productId: "String",
    quantity: "Int",
    amount: "Decimal",
  },
  payment: {
    paymentId: "String",
    employeeId: "String",
    saleId: "String",
    reservationId: "String",
    invoice: "String",
    hash: "String",
    fromAccountId: "String",
    toAccountId: "String",
    currency: "String",
    amount: "Decimal",
    externalRef: "String",
    status: "String",
  },
  shift: {
    shiftId: "String",
    employeeId: "String",
    shiftCode: "String",
    openKhmerRiel: "Decimal",
    openUsDollar: "Decimal",
    openTime: "Date",
    closeKhmerRiel: "Decimal",
    closeUsDollar: "Decimal",
    closeTime: "Date",
    status: "String",
  },
  bankNote: {
    bankNoteId: "String",
    shiftId: "String",
    khmer100: "Int",
    khmer500: "Int",
    khmer1K: "Int",
    khmer2K: "Int",
    khmer5K: "Int",
    khmer10K: "Int",
    khmer15K: "Int",
    khmer20K: "Int",
    khmer30K: "Int",
    khmer50K: "Int",
    khmer100K: "Int",
    khmer200K: "Int",
    us1: "Int",
    us5: "Int",
    us10: "Int",
    us20: "Int",
    us50: "Int",
    us100: "Int",
    status: "String",
  },
  groupMessage: {
    groupMessageId: "String",
    employeeId: "String",
    content: "String",
    time: "Date",
  },
  log: {
    id: "String",
    method: "String",
    url: "String",
    status: "Int",
    responseTime: "Float",
    ip: "String",
    userAgent: "String",
  },
  authLog: {
    id: "String",
    authId: "String",
    method: "String",
    url: "String",
    status: "Int",
    responseTime: "Float",
    ip: "String",
    userAgent: "String",
  },
};

module.exports = { modelSchemas };
