const modelSchemas = {
  role: {
    role_id: "Int",
    name: "String",
  },
  auth: {
    auth_id: "Int",
    email: "String",
    password: "String",
    role_id: "Int",
    employee_id: "Int",
    customer_id: "Int",
    status: "String",
  },
  attendace: {
    attendace_id: "Int",
    employee_id: "Int",
    datetime: "Date",
    note: "String",
  },
  employee: {
    employee_id: "Int",
    employee_code: "String",
    first_name: "String",
    last_name: "String",
    gender: "String",
    dob: "DateTime",
    phone: "String",
    position_id: "Int",
    department_id: "Int",
    salary: "Int",
    hired_date: "DateTime",
    status: "String",
  },
  employeeInfo: {
    info_id: "Int",
    employee_id: "Int",
    picture: "String",
    region: "String",
    email: "String",
    address: "String",
    city_id: "Int",
    state_id: "Int",
    country: "String",
    note: "String",
  },
  department: {
    department_id: "Int",
    department_name: "String",
    department_code: "String",
    memo: "String",
    status: "String",
  },
  position: {
    position_id: "Int",
    department_id: "Int",
    position_name: "String",
    position_code: "String",
    memo: "String",
    status: "String",
  },
  customer: {
    customer_id: "Int",
    first_name: "String",
    last_name: "String",
    picture: "String",
    gender: "String",
    email: "String",
    phone: "String",
    address: "String",
    city_id: "Int",
    state_id: "Int",
    status: "String",
  },
  reservationDetail: {
    reserve_detail_id: "Int",
    room_id: "Int",
    employee_id: "Int",
    customer_id: "Int",
    reservation_id: "Int",
    price: "Decimal",
    night: "Int",
    amount: "Decimal",
  },
  reservation: {
    reservation_id: "Int",
    checkin_date: "Date",
    checkout_date: "Date",
    is_checkin: "Boolean",
    is_checkout: "Boolean",
    reservation_type: "String",
    adults: "Int",
    children: "Int",
    payment_status: "String",
    payment_method: "String",
    memo: "String",
    status: "String",
  },
  room: {
    room_id: "Int",
    roomtype_id: "Int",
    room_name: "String",
    price: "Decimal",
    is_ac: "Boolean",
    capacity: "Int",
    size: "Int",
    discount_rate: "Int",
    is_booked: "Boolean",
    status: "String",
  },
  roomType: {
    roomtype_id: "Int",
    type_name: "String",
    type_code: "String",
  },
  product: {
    product_id: "Int",
    product_name: "String",
    product_code: "String",
    product_category_id: "Int",
    picture: "String",
    price: "Decimal",
    discount_rate: "Int",
    status: "String",
  },
  productCategory: {
    product_category_id: "Int",
    picture: "String",
    category_name: "String",
    category_code: "String",
    memo: "String",
    status: "String",
  },
  cart: {
    cart_id: "Int",
    auth_id: "Int",
    product_id: "Int",
    quantity: "Int",
  },
  cartNote: {
    note_id: "Int",
    cart_id: "Int",
    note: "String",
  },
  productStock: {
    product_stock_id: "Int",
    product_id: "Int",
    supplier_id: "Int",
    inv_number: "String",
    product_add: "Int",
    add_price: "Decimal",
    add_date: "Date",
    memo: "String",
    status: "String",
  },
  supplier: {
    supplier_id: "Int",
    supplier_name: "String",
    company_name: "String",
    phone: "String",
    email: "String",
    address: "String",
    status: "String",
    created_at: "Date",
  },
  sale: {
    sale_id: "Int",
    employee_id: "Int",
    room_id: "Int",
    customer_id: "Int",
    sale_date: "Date",
    amount: "Decimal",
    status: "String",
  },
  saleDetail: {
    sale_detail_id: "Int",
    sale_id: "Int",
    product_id: "Int",
    quantity: "Int",
    amount: "Decimal",
  },
  payment: {
    payment_id: "Int",
    employee_id: "Int",
    sale_id: "Int",
    reservation_id: "Int",
    invoice: "String",
    hash: "String",
    fromAccountId: "String",
    toAccountId: "String",
    currency: "String",
    amount: "Decimal",
    externalRef: "String",
    status: "String",
  },
  shift: {
    shift_id: "Int",
    employee_id: "Int",
    shift_code: "String",
    open_khmer_riel: "Decimal",
    open_us_dollar: "Decimal",
    open_time: "Date",
    close_khmer_riel: "Decimal",
    close_us_dollar: "Decimal",
    close_time: "Date",
    status: "String",
  },
  bankNote: {
    bank_note_id: "Int",
    shift_id: "Int",
    khmer_100: "Int",
    khmer_500: "Int",
    khmer_1K: "Int",
    khmer_2K: "Int",
    khmer_5K: "Int",
    khmer_10K: "Int",
    khmer_15K: "Int",
    khmer_20K: "Int",
    khmer_30K: "Int",
    khmer_50K: "Int",
    khmer_100K: "Int",
    khmer_200K: "Int",
    us_1: "Int",
    us_5: "Int",
    us_10: "Int",
    us_20: "Int",
    us_50: "Int",
    us_100: "Int",
    status: "String",
  },
  groupMessage: {
    group_message_id: "Int",
    employee_id: "Int",
    content: "String",
    time: "Date",
  },
  log: {
    id: "Int",
    method: "String",
    url: "String",
    status: "Int",
    response_time: "Float",
    ip: "String",
    user_agent: "String",
  },
  authLog: {
    id: "Int",
    auth_id: "Int",
    method: "String",
    url: "String",
    status: "Int",
    response_time: "Float",
    ip: "String",
    user_agent: "String",
  },
};

module.exports = { modelSchemas };
